# The iOS half of `marsrs-react-native-xlog`.
#
# `marsrs-xlog.xcframework` is carried here and not resolved: CocoaPods cannot
# take the SwiftPM binary target of Package.swift, and there is no pod for it,
# so `.github/workflows/release.yml` drops the release's framework into
# `ios/Frameworks/` before the package is packed. `ios/include/mars_xlog.h` is
# the C ABI's own header, copied by `scripts/package_react_native.sh` out of
# `crates/marsrs-ffi/include` rather than kept here, so it cannot drift from it.
#
# The glue is Swift — `ios/Xlog.swift` — over the C header the framework
# carries, because `MarsRSFFI`, the module SwiftPM makes of the two, is nothing
# CocoaPods can hand a pod: `ios/Xlog-Bridging-Header.h` is what shows the Swift
# `mars_xlog.h`, and `ios/Xlog.mm` is the one file of the module that has no
# Swift spelling, which its own header says why.
#
# `React-Codegen` is what `src/NativeXlog.ts` is generated by: `NativeXlogSpec`,
# the protocol, and `NativeXlogSpecJSI`, the C++ class `Xlog.mm` hands React
# Native — a pod of the app's own `use_react_native!`, and the pod the generated
# headers land in.
#
# The version is package.json's, and not a number of its own: one place a
# release stamps.

require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = package["name"]
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.author       = { "orangeboyChen" => "https://github.com/orangeboyChen" }
  s.source       = { :git => "https://github.com/orangeboyChen/mars-rs.git",
                     :tag => "v#{s.version}" }
  # What Package.swift declares for iOS; the framework's own floor.
  s.platform     = :ios, "12.0"
  s.swift_version = "5.0"
  s.source_files = "ios/*.{h,mm,swift}"
  s.vendored_frameworks = "ios/Frameworks/marsrs-xlog.xcframework"
  s.preserve_paths = "ios/include/mars_xlog.h"
  # One header for the pod's Swift to be bridged to the C ABI with, and one for
  # the app's to be bridged to this pod's ObjC with. The first is the module's
  # own; the second is the one CocoaPods reads when it compiles a pod that mixes
  # the two languages.
  s.xcconfig     = { "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/ios/include\"",
                     "SWIFT_OBJC_BRIDGING_HEADER" => "\"$(PODS_TARGET_SRCROOT)/ios/Xlog-Bridging-Header.h\"" }
  # `iana-time-zone` calls `CFTimeZone*`, and a Rust static library carries no
  # link flags of its own: Package.swift names the framework for the same reason.
  s.frameworks   = "CoreFoundation"
  # React Native's own, in place of `s.dependency "React-Core"`: it is what the
  # app's `use_react_native!` provides, and it keeps the pod off a version of
  # React Native the app did not choose.
  install_modules_dependencies(s)
  s.dependency "React-Codegen"
end
