// The React Native demo of mars-rs: one screen, one button, six records into a
// `.xlog` file.
//
// This is the app's `App.tsx` and not a whole React Native project: the
// `android/` and `ios/` halves of one are generated by React Native's own CLI —
// an Xcode project, a Gradle build and a few hundred files in between — and a
// repository that checked them in would be checking in a tree that is one
// `npx @react-native-community/cli init` away. So:
//
//     npx @react-native-community/cli init MarsRSDemo
//     cd MarsRSDemo && npm install marsrs-react-native-xlog react-native-fs
//     cd ios && pod install && cd ..
//     npx react-native run-android      # or run-ios
//
// and then replace the `App.tsx` the CLI wrote with this one. `README.md` next
// to this file says the same four lines again, with what to look at when they
// are done.
//
// What is React Native's here is the directory: JavaScript has no way to ask
// where an app may write, so `react-native-fs` answers it, and the appender is
// opened in an effect rather than at module scope for the same reason — the
// answer is not there yet when this file is evaluated.

import React, {useEffect, useState} from 'react';
import {Button, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import RNFS from 'react-native-fs';
import {
  AppenderMode,
  CompressMode,
  LogLevel,
  Xlog,
} from 'marsrs-react-native-xlog';

/** The prefix of every file: `marsrs_YYYYMMDD.xlog`. */
const NAME_PREFIX = 'marsrs';

/** How many bytes a file is closed at: 8 MiB. */
const MAX_FILE_SIZE = 8 * 1024 * 1024;

/** How many seconds a file is kept: ten days. */
const MAX_ALIVE_TIME = 10 * 24 * 60 * 60;

/** One record at every level, in this order. */
const RECORDS: [LogLevel, string, string][] = [
  [LogLevel.verbose, 'trace', 'the finest record there is'],
  [LogLevel.debug, 'net', 'resolved 3 addresses for example.com'],
  [LogLevel.info, 'startup', 'cold start in 412 ms'],
  [LogLevel.warning, 'net', 'retrying after 1204 ms'],
  [LogLevel.error, 'login', 'login failed: token expired'],
  [LogLevel.fatal, 'login', 'giving up after 3 attempts'],
];

/**
 * Opens the appender, and says why when it does not.
 *
 * `Xlog.open` throws — on an empty `logDir`, and on one the process cannot write
 * to — and an app that lets that reach the render is an app that red-boxes on a
 * device whose storage is full. So the reason comes back as a string and the
 * screen shows it.
 */
function openXlog(): {xlog?: Xlog; failure?: string} {
  // `DocumentDirectoryPath` is the directory the platform gives this app: the
  // app's own, backed up, and the one a log belongs in. `CachesDirectoryPath`
  // is the one the OS empties when space runs short, which is exactly when a
  // log matters.
  const logDir = `${RNFS.DocumentDirectoryPath}/xlog`;
  try {
    const xlog = Xlog.open({
      // The one option with no default — the appender is not opened without it.
      // The rest are the C++'s own: `compressMode` defaults to `.zlib`, and a
      // `cacheDir` left out puts the mmap cache beside the files.
      logDir,
      cacheDir: `${RNFS.DocumentDirectoryPath}/xlog-cache`,
      namePrefix: NAME_PREFIX,
      // Verbose so that all six records survive to be read back. An app that
      // ships sets `LogLevel.info`, and `LogLevel.none` for a build that writes
      // nothing at all.
      level: LogLevel.verbose,
      // `async` hands the record to a writer thread and returns — the whole
      // point of the pipeline is that a log call does not block the thread that
      // made it.
      mode: AppenderMode.async,
      compressMode: CompressMode.zlib,
    });
    // Mirror every record to the console as well, so Metro's log shows what went
    // into the file. Off in a build that ships.
    xlog.consoleLogEnabled = __DEV__;
    // Close a file at 8 MiB and drop one at ten days. Both start at 0, which is
    // not the same 0 twice: a maximum size of 0 never splits a file, and a
    // lifetime of 0 is the C++'s own ten days.
    xlog.maxFileSizeBytes = MAX_FILE_SIZE;
    xlog.maxAliveTimeSeconds = MAX_ALIVE_TIME;
    return {xlog};
  } catch (error) {
    return {failure: error instanceof Error ? error.message : String(error)};
  }
}

/**
 * The app: what the appender is writing into, and a button that writes six
 * records through it.
 */
export default function App(): React.JSX.Element {
  // The appender, held in state and not in a module-level variable, so that the
  // screen redraws once it exists: `Xlog.open` needs `DocumentDirectoryPath`,
  // which is not an answer JavaScript has before the effect runs.
  const [xlog, setXlog] = useState<Xlog | undefined>(undefined);
  const [status, setStatus] = useState('opening the appender');

  useEffect(() => {
    const opened = openXlog();
    if (opened.xlog === undefined) {
      setStatus(`no appender: ${opened.failure}`);
      return;
    }
    setXlog(opened.xlog);
    setStatus(`writing into ${opened.xlog.namePrefix}_<YYYYMMDD>.xlog`);

    // Closing on unmount is what keeps the last records from going with the
    // process: with an async appender, what `close` drains is what the writer
    // thread still held.
    return () => opened.xlog?.close();
  }, []);

  /** Writes one record at every level, and waits for all of them to land. */
  const writeDemoRecords = (): void => {
    if (xlog === undefined) {
      return;
    }
    // The same six `demo/rust`, `demo/c`, `demo/android` and `demo/kmp` write,
    // in the same order, so that the five read side by side.
    for (const [level, tag, message] of RECORDS) {
      xlog.log(level, tag, message);
    }
    // A message that is expensive to build is worth asking about first: a
    // record the level drops still costs its caller the string.
    if (xlog.isLoggable(LogLevel.debug)) {
      xlog.d('startup', `the appender is ${xlog.namePrefix}`);
    }
    // `true` waits for the write, so every record above is on disk when this
    // returns. An app calls it before it reads the files or uploads them.
    xlog.flush(true);
    setStatus('six records written and flushed');
  };

  return (
    <SafeAreaView style={styles.screen}>
      <View style={styles.body}>
        <Text style={styles.status}>{status}</Text>
        <Button
          title="Write six records"
          // Off when there is no appender: a button that writes nowhere is a
          // button that looks broken when it is tapped.
          disabled={xlog === undefined}
          onPress={writeDemoRecords}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  body: {
    flex: 1,
    gap: 24,
    justifyContent: 'center',
    padding: 24,
  },
  status: {
    fontFamily: 'monospace',
  },
});
