// The Kotlin Multiplatform module of the whole port: `marsrs-kmp`, the pair
// `xlog-kmp` is the logging half of, the way the two crates on crates.io
// are a pair, `mars-core` and `mars-xlog` are the C++ project's, and `MarsRS`
// and `MarsRSXlog` are the pair `Package.swift` exposes.
//
// The API it exposes is `:marsrs-xlog`'s — re-exported twice over, by an `api`
// dependency, which is what puts `Xlog` on a consumer's classpath and the
// cinterop archive into a consumer's link, and by the typealiases of
// `src/commonMain` — plus the net half, which is this module's own: STN and SDT
// in `src/commonMain` as one `expect` each, and one `actual` per platform
// family, over the JNI bridge of `crates/marsrs-jni` on Android and over the
// C ABI of `crates/marsrs-ffi` on every Kotlin/Native target.
//
// That is the whole reason this module is a module and not a second name of
// `:marsrs-xlog`: an app that depends on `marsrs-kmp` gets the whole port, and
// one that depends on `xlog-kmp` carries no byte of the task pipeline's. Which
// is why the two archives `scripts/build_kmp_native.sh` writes are two, and why
// the cinterop below embeds the net one and not xlog's.

import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.multiplatform")
    id("maven-publish")
}

val publishedGroup: String = (findProperty("publishedGroup") as String?) ?: "io.github.orangeboychen.marsrs"
val publishedArtifact: String = (findProperty("publishedArtifact") as String?) ?: "marsrs-kmp"
val publishedVersion: String = (findProperty("publishedVersion") as String?) ?: "0.0.0"

// Where the native libraries come from: one directory per Kotlin target, named
// after it, plus `android/<abi>` for the .so files of the JNI bridge. The two
// names are the two archives `scripts/build_kmp_native.sh` writes; this module
// asks for the net one, and `:marsrs-xlog` for xlog's.
//
// `android/` is *not* packaged by this module, and the name is here so the
// check at the bottom can skip it: the `Java_*` symbols `src/androidMain` calls
// — `StnLogic` and `SdtLogic` over `libmarsrsxlog.so` — are in the AAR of
// `:marsrs-xlog`, which `commonMain` takes as an `api` dependency and which
// packages that very directory. An AAR of this one that carried the same
// `jni/<abi>/libmarsrsxlog.so` would be a second copy of one file: AGP's native
// merge of a consumer that depends on both fails on it, and every consumer
// would have to add a `pickFirst` to build at all.
val nativeDir: File = rootProject.file("native")
val androidNativeDir: File = File(nativeDir, "android")
// The two headers of the net half, which are checked in next to the crate:
// cinterop reads them out of the repository and not out of a copy, so the two
// cannot drift.
val headerDir: File = rootProject.file("../../crates/marsrs-ffi/include")

// The checked-in cinterop definition, and one copy of it per target in the
// build directory: everything in it is the same for every target except the two
// absolute paths — which headers to read and which archive to embed — and those
// are the lines this build appends.
val defTemplate: File = file("src/nativeInterop/cinterop/mars_net.def")
val generatedDefDir: File = layout.buildDirectory.dir("generated/cinterop").get().asFile

fun defFileFor(target: String): File {
    val lib = File(nativeDir, target)
    val dir = File(generatedDefDir, target)
    dir.mkdirs()
    return File(dir, "mars_net.def").apply {
        writeText(
            """
            # Generated by marsrs/build.gradle.kts from
            # src/nativeInterop/cinterop/mars_net.def — do not edit.
            ${defTemplate.readText().trimEnd()}
            compilerOpts = -I${headerDir.absolutePath}
            libraryPaths = ${lib.absolutePath}

            """.trimIndent()
        )
    }
}

kotlin {
    // `expect`/`actual` of an object — `StnLogic` and `SdtLogic` are two — is
    // Beta in Kotlin 2.2, and the flag is what opts in.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvmToolchain(17)

    androidTarget {
        publishLibraryVariants("release")
    }

    // The same targets as `marsrs-xlog`: a Kotlin Multiplatform publication is
    // one artifact per target, so a module that left one out would be a module
    // an app of that platform cannot resolve.
    iosArm64()
    iosX64()
    iosSimulatorArm64()
    macosX64()
    macosArm64()
    watchosArm64()
    watchosDeviceArm64()
    watchosSimulatorArm64()
    tvosArm64()
    tvosSimulatorArm64()
    linuxX64()
    linuxArm64()
    mingwX64()

    // `marsrs-ffi`'s net half through cinterop, once per Kotlin/Native target.
    targets.withType<KotlinNativeTarget>().configureEach {
        val kotlinTarget = this
        compilations.getByName("main").cinterops.create("marsNetFFI") {
            defFile(defFileFor(kotlinTarget.name))
        }
    }

    sourceSets {
        commonMain.dependencies {
            api(project(":marsrs-xlog"))
        }
    }
}

android {
    namespace = "io.github.orangeboychen.marsrs"
    compileSdk = 36

    defaultConfig {
        // `marsrs-jni` is built against NDK 27 / API 24; 21 is the floor the C++
        // project ships with.
        minSdk = 21

        // The rules an app's R8 has to have for the net half, carried in the AAR
        // as `proguard.txt`: `:marsrs-xlog` ships its own for `xlog.*`, and
        // those travel with the dependency, but nothing keeps the classes
        // `src/androidMain` puts in front of `marsrs-jni` — `stn.StnLogic`,
        // `stn.Task`, `sdt.SdtLogic` and the `Answer` a probe is read out of —
        // which the bridge reaches by name through JNI.
        consumerProguardFiles("consumer-rules.pro")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

publishing {
    // GitHub Packages, the host `marsrs-xlog` is published to and the reason it
    // is named here too: Gradle publishes one module at a time, and this one is
    // the coordinate an app depends on.
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/orangeboyChen/mars-rs")
            credentials {
                username = (findProperty("mavenUser") as String?) ?: System.getenv("GITHUB_ACTOR")
                password = (findProperty("mavenPassword") as String?) ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

// Named after the evaluation, for the same reason `marsrs-xlog` names its own
// there: the artifactId of the Android publication is AGP's to write, and it
// writes it after `publishing { }` has run.
afterEvaluate {
    publishing.publications.withType<MavenPublication>().configureEach {
        artifactId = if (name == "kotlinMultiplatform") {
            publishedArtifact
        } else {
            "$publishedArtifact-${name.lowercase()}"
        }
        groupId = publishedGroup
        version = publishedVersion

        pom {
            name.set(publishedArtifact)
            description.set("Kotlin Multiplatform library of the Rust port of Tencent/mars: xlog, STN and SDT")
            url.set("https://github.com/orangeboyChen/mars-rs")
            licenses {
                license {
                    name.set("MIT")
                    url.set("https://github.com/orangeboyChen/mars-rs/blob/main/LICENSE")
                }
            }
        }
    }

    // `marsrs-kmp` without the archive of the net half in it is `xlog-kmp` under
    // another name, and Gradle would publish it all the same — one archive is
    // missing and the klib of that target links nothing. So fail loudly, the way
    // `marsrs-xlog` does: `marsrs-kmp-native.zip` of the release carries them.
    val netDirs = nativeDir.listFiles()?.filter { it.isDirectory && it.name != androidNativeDir.name } ?: emptyList()
    val withoutNet = netDirs.filter { !File(it, "libmars_net_ffi.a").isFile }
    if (withoutNet.isNotEmpty()) {
        throw GradleException(
            "No libmars_net_ffi.a in ${withoutNet.joinToString { it.name }}. " +
                "Run scripts/build_kmp_native.sh, or download marsrs-kmp-native.zip of the " +
                "release into $nativeDir (see the 'kmp' job of .github/workflows/release.yml)."
        )
    }
}
