// The Kotlin Multiplatform module of the xlog half of mars-rs.
//
// One API in `commonMain`, and one `actual` of it per platform family:
//
//   * `androidMain` — the JNI bridge of `crates/marsrs-jni`, the same
//     `Java_io_github_orangeboychen_marsrs_xlog_Xlog_*` symbols the AAR in
//     `platforms/android/marsrs-xlog` calls.
//   * `nativeMain`  — the C ABI of `crates/marsrs-ffi` (`mars_xlog.h`) through
//     cinterop, for every Kotlin/Native target: iOS, watchOS, tvOS, macOS,
//     Linux and Windows.
//
// Nothing is compiled from Rust here. Neither JitPack nor a plain `./gradlew`
// has a Rust toolchain, every Kotlin/Native target needs its own archive, and
// an Apple one cannot even be cross-compiled from Linux — so
// .github/workflows/release.yml builds them and lays them out as
// `native/<kotlin-target>/`; `scripts/build_kmp_native.sh` is what it runs.
//
// The archive is copied into the klib by cinterop, so an app that depends on
// this module links `marsrs-ffi` without being told where it is — the shape a
// Kotlin Multiplatform library carries a vendored C library in.

import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.multiplatform")
    id("maven-publish")
}

val publishedGroup: String = (findProperty("publishedGroup") as String?) ?: "io.github.orangeboychen.marsrs"
val publishedArtifact: String = (findProperty("publishedArtifact") as String?) ?: "xlog-kmp"
val publishedVersion: String = (findProperty("publishedVersion") as String?) ?: "0.0.0"

// Where the native libraries come from: one directory per Kotlin target, named
// after it, plus `android/<abi>` for the .so files of the JNI bridge.
val nativeDir: File = rootProject.file("native")
val androidNativeDir: File = File(nativeDir, "android")
// The C ABI's header, which is checked in next to the crate: cinterop reads it
// out of the repository and not out of a copy, so the two cannot drift.
val headerDir: File = rootProject.file("../../crates/marsrs-ffi/include")

// The checked-in cinterop definition, and one copy of it per target in the
// build directory: everything in it is the same for every target except the two
// absolute paths — which header to read and which archive to embed — and those
// are the lines this build appends.
val defTemplate: File = file("src/nativeInterop/cinterop/mars_ffi.def")
val generatedDefDir: File = layout.buildDirectory.dir("generated/cinterop").get().asFile

fun defFileFor(target: String): File {
    val lib = File(nativeDir, target)
    val dir = File(generatedDefDir, target)
    dir.mkdirs()
    return File(dir, "mars_ffi.def").apply {
        writeText(
            """
            # Generated by marsrs-xlog/build.gradle.kts from
            # src/nativeInterop/cinterop/mars_ffi.def — do not edit.
            ${defTemplate.readText().trimEnd()}
            compilerOpts = -I${headerDir.absolutePath}
            libraryPaths = ${lib.absolutePath}

            """.trimIndent()
        )
    }
}

kotlin {
    // `expect`/`actual` of a class — of an `object`, here — is Beta in Kotlin
    // 2.2, and the flag is what opts in. It is the only way `commonMain` gets to
    // say `Xlog`: the alternative is a common interface plus an `expect val`,
    // which is one more type on every platform to name one appender.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    // Kotlin/Native: 17. JVM and Android: the JDK the Kotlin compiler emits
    // for, which is the one `crates/marsrs-jni` asks for on the other side.
    jvmToolchain(17)

    androidTarget {
        publishLibraryVariants("release")
    }

    // Every Kotlin/Native target the release ships an archive for. Two Kotlin
    // targets are not in the list, and both are missing because Rust has no
    // target for them: `watchosX64` and `tvosX64`, the x86_64 simulators —
    // `x86_64-apple-watchos-sim` and `x86_64-apple-tvos` are not triples
    // `rustup` knows. A simulator on an Intel Mac is the only thing that would
    // want either, and `scripts/build_xcframework.sh` gives the reason a
    // watchOS one is not missed: a watchOS simulator is arm64.
    iosArm64()
    iosX64()
    iosSimulatorArm64()
    macosX64()
    macosArm64()
    watchosArm64()
    watchosDeviceArm64()
    watchosSimulatorArm64()
    tvosArm64()
    tvosSimulatorArm64()
    linuxX64()
    linuxArm64()
    mingwX64()

    // `marsrs-ffi` through cinterop, once per Kotlin/Native target.
    targets.withType<KotlinNativeTarget>().configureEach {
        val kotlinTarget = this
        compilations.getByName("main").cinterops.create("marsFFI") {
            defFile(defFileFor(kotlinTarget.name))
        }
    }

    sourceSets {
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "io.github.orangeboychen.marsrs.xlog"
    compileSdk = 36

    defaultConfig {
        // `marsrs-jni` is built against NDK 27 / API 24; 21 is the floor the C++
        // project ships with.
        minSdk = 21

        // The Android target of this module is JNI and not cinterop, so it
        // needs the same rules `platforms/android/marsrs-xlog` ships: carried
        // in the Android AAR as `proguard.txt`, and merged into the app's own
        // rules by AGP. `platforms/kmp/marsrs` needs no file of its own — it
        // is this module's API re-exported, and consumer rules travel with
        // the dependency.
        consumerProguardFiles("consumer-rules.pro")
    }

    sourceSets {
        getByName("main") {
            jniLibs.srcDirs(androidNativeDir)
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }

    // AGP publishes nothing until a variant is named: this is what makes
    // `components["release"]` exist for the publication below.
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

publishing {
    // GitHub Packages: the only maven host a release of this repository can
    // publish to without a key it does not have — JitPack builds on Linux only,
    // so it cannot produce the Apple klibs, and Maven Central wants a signature
    // this workflow cannot make. A consumer reads it with the repository below
    // and a token of their own; `marsrs-kmp-maven.zip` on the release is the same
    // repository for one that would rather not authenticate at all.
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/orangeboyChen/mars-rs")
            credentials {
                username = (findProperty("mavenUser") as String?) ?: System.getenv("GITHUB_ACTOR")
                password = (findProperty("mavenPassword") as String?) ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

afterEvaluate {
    publishing.publications.withType<MavenPublication>().configureEach {
        // Kotlin names a publication after the target it publishes: the root
        // one after nothing, and the rest `<project>-<target>`.
        //
        // It is named here and not in `publishing { }` because the Android one
        // is not Kotlin's to name: AGP writes the artifactId of the AAR itself,
        // and it does that *after* the `publishing` block has run — so a rename
        // of it there is overwritten by `marsrs-xlog-android`.
        //
        // `-android` and not `-androidrelease`, which is what
        // `name.lowercase()` makes of the publication AGP registers: it is
        // named `androidRelease`, after the build variant, and this module
        // publishes one — `publishLibraryVariants("release")` — so which
        // variant it is is nothing a consumer can pick. The suffix is what
        // a reader meets twice: in the listing of GitHub Packages, and in
        // the tree of `marsrs-kmp-maven.zip`.
        artifactId = when (name) {
            "kotlinMultiplatform" -> publishedArtifact
            "androidRelease" -> "$publishedArtifact-android"
            else -> "$publishedArtifact-${name.lowercase()}"
        }
        groupId = publishedGroup
        version = publishedVersion

        pom {
            name.set(publishedArtifact)
            description.set("Kotlin Multiplatform library of the Rust port of Tencent/mars: xlog")
            url.set("https://github.com/orangeboyChen/mars-rs")
            licenses {
                license {
                    name.set("MIT")
                    url.set("https://github.com/orangeboyChen/mars-rs/blob/main/LICENSE")
                }
            }
        }
    }

    // A module without a native library in it is worthless, and Gradle would
    // publish it all the same, so fail loudly instead. The check is
    // orangeboyChen/mars', and it is the one
    // `platforms/android/marsrs-xlog` makes.
    if (!nativeDir.isDirectory) {
        throw GradleException(
            "No native libraries found in $nativeDir. Run scripts/build_kmp_native.sh, " +
                "or download marsrs-kmp-native.zip of the release into it " +
                "(see the 'kmp' job of .github/workflows/release.yml)."
        )
    }
    val abis = androidNativeDir.listFiles()?.filter { it.isDirectory } ?: emptyList()
    if (abis.isEmpty()) {
        throw GradleException(
            "No native libraries found in $androidNativeDir. Unpack marsrs-android-native.zip " +
                "of the release into it first (see the 'android' job of " +
                ".github/workflows/release.yml)."
        )
    }
    println("marsrs-xlog: packaging ${abis.map { it.name }.sorted().joinToString(", ")}")
}
